@extends('backend.app')

@section('title', 'Work Calendar')

@section('content')
    <div class="app-content main-content mt-0">
        <div class="side-app">
            <div class="main-container container-fluid" style="padding: 0;">

                {{-- page header --}}
                <div class="page-header">
                    <div class="card shadow-sm mb-2 border-0">
                        <div class="card-body d-flex justify-content-between align-items-center flex-wrap">
                            <div>
                                <h1 class="page-title mb-0">Calendar For Work Management</h1>
                            </div>
                        </div>
                    </div>
                </div>
                {{-- page header end --}}

                {{-- calendar integration --}}
                <div class="calendar-container">
                    <!-- Sidebar -->
                    <div class="calendar-sidebar">
                        <div class="sidebar-header">
                            <button class="create-btn" data-bs-toggle="modal" data-bs-target="#createWorkModal">
                                <i class="fas fa-plus"></i>
                                <span>Create</span>
                            </button>
                        </div>

                        <!-- Scrollable Content -->
                        <div class="sidebar-scrollable">
                            <!-- Mini Calendar -->
                            <div class="mini-calendar">
                                <div class="mini-calendar-header">
                                    <button class="mini-nav-btn" id="miniPrevMonth">
                                        <i class="fas fa-chevron-left"></i>
                                    </button>
                                    <span class="mini-calendar-title" id="miniCalendarTitle">October 2025</span>
                                    <button class="mini-nav-btn" id="miniNextMonth">
                                        <i class="fas fa-chevron-right"></i>
                                    </button>
                                </div>
                                <div class="mini-calendar-grid" id="miniCalendarGrid">
                                    <!-- Calendar days will be generated by JavaScript -->
                                </div>
                            </div>

                            <!-- MY CALENDARS SECTION - NEW -->
                            <div class="my-calendars-section">
                                <div class="calendars-header">
                                    <span class="calendars-title">My Calendars</span>
                                    <button class="add-calendar-btn" onclick="openAddCalendarModal()">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                </div>
                                <div class="calendar-list-container" id="calendarListContainer">
                                    <div class="loading-calendars">
                                        <i class="fas fa-spinner fa-spin"></i> Loading calendars...
                                    </div>
                                </div>
                            </div>

                            <!-- Filters -->
                            <div class="sidebar-filters">
                                <div class="filter-group">
                                    <label class="filter-label">Team</label>
                                    <select id="teamFilter" class="filter-select">
                                        <option value="" style="font-size: 10px">All Teams</option>
                                        @foreach ($teams as $team)
                                            <option value="{{ $team->id }}">{{ $team->name }}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <div class="filter-group">
                                    <label class="filter-label">Status</label>
                                    <select id="statusFilter" class="filter-select">
                                        <option value="">All Status</option>
                                        <option value="completed">Completed</option>
                                        <option value="pending">Pending</option>
                                        <option value="rescheduled">Rescheduled</option>
                                    </select>
                                </div>

                                <div class="filter-group">
                                    <label class="filter-label">Category</label>
                                    <select id="categoryFilter" class="filter-select">
                                        <option value="">All Categories</option>
                                        @foreach ($categories as $category)
                                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <div class="google-sync-section">
                                    <div class="sync-status">
                                        <i class="fab fa-google"></i>
                                        <span>Google Calendar</span>
                                        @if ($isGoogleConnected)
                                            <span class="status-badge connected">
                                                <i class="fas fa-check-circle"></i>
                                                Connected
                                            </span>
                                        @else
                                            <span class="status-badge disconnected">
                                                <i class="fas fa-times-circle"></i>
                                                Not Connected
                                            </span>
                                        @endif
                                    </div>
                                    <div class="sync-actions">
                                        @if ($isGoogleConnected)
                                            <button class="sync-btn primary btn btn-sm" id="syncGoogleBtn"
                                                style="flex: 0 0 calc(80% - 4px);">
                                                <i class="fas fa-sync"></i> Sync All
                                            </button>
                                            <a href="{{ route('google.disconnect') }}" class="sync-btn"
                                                style="flex: 0 0 calc(20% - 4px); display: flex; align-items: center; justify-content: center; text-decoration: none; color: #5f6368;">
                                                <i class="fas fa-unlink"></i>
                                            </a>
                                        @else
                                            <a href="{{ route('google.redirect') }}" class="sync-btn primary btn btn-sm"
                                                style="flex: 1; text-align: center; text-decoration: none; color: white;">
                                                <i class="fab fa-google"></i> Connect
                                            </a>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Main Calendar -->
                    <div class="calendar-main">
                        <div class="calendar-header">
                            <div class="calendar-header-left">
                                <button class="today-btn" id="todayBtn">Today</button>
                                <div class="calendar-nav">
                                    <button class="nav-btn" id="prevBtn">
                                        <i class="fas fa-chevron-left"></i>
                                    </button>
                                    <button class="nav-btn" id="nextBtn">
                                        <i class="fas fa-chevron-right"></i>
                                    </button>
                                </div>
                                <h2 class="calendar-title" id="calendarTitle">October 2025</h2>
                            </div>
                            <div class="calendar-header-right">
                                {{-- <button class="print-btn" id="printCalendarBtn">
                                    <i class="fas fa-print"></i> Print
                                </button> --}}
                                <div class="view-switcher">
                                    <button class="view-btn active" data-view="timeGridDay">Day</button>
                                    <button class="view-btn" data-view="timeGridWeek">Week</button>
                                    <button class="view-btn" data-view="dayGridMonth">Month</button>
                                </div>
                            </div>
                        </div>
                        <div class="calendar-content">
                            <div id="calendar"></div>
                        </div>
                    </div>
                </div>
                {{-- calendar integration end --}}
            </div>
        </div>
    </div>

    <!-- CREATE/EDIT WORK MODAL -->
    @include('backend.layouts.calendar.add_edit')

    <!-- VIEW EVENT DETAILS MODAL -->
    @include('backend.layouts.calendar.view')

    <!-- ADD/EDIT CALENDAR MODAL -->
    <div class="modal fade" id="addCalendarModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="calendarModalTitle">
                        <i class="fas fa-calendar-plus me-2"></i>Add Calendar
                    </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <form id="calendarForm">
                        <input type="hidden" id="calendarId">
                        <div class="mb-3">
                            <label class="form-label">Calendar Name *</label>
                            <input type="text" class="form-control" id="calendarName" required>
                            <span class="text-danger error-text calendar_name_error"></span>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Color *</label>
                            <div class="color-picker-grid">
                                <label class="color-option">
                                    <input type="radio" name="calendar_color" value="#7986cb" checked>
                                    <span class="color-box" style="background: #7986cb;"></span>
                                </label>
                                <label class="color-option">
                                    <input type="radio" name="calendar_color" value="#33b679">
                                    <span class="color-box" style="background: #33b679;"></span>
                                </label>
                                <label class="color-option">
                                    <input type="radio" name="calendar_color" value="#8e24aa">
                                    <span class="color-box" style="background: #8e24aa;"></span>
                                </label>
                                <label class="color-option">
                                    <input type="radio" name="calendar_color" value="#e67c73">
                                    <span class="color-box" style="background: #e67c73;"></span>
                                </label>
                                <label class="color-option">
                                    <input type="radio" name="calendar_color" value="#f6bf26">
                                    <span class="color-box" style="background: #f6bf26;"></span>
                                </label>
                                <label class="color-option">
                                    <input type="radio" name="calendar_color" value="#f4511e">
                                    <span class="color-box" style="background: #f4511e;"></span>
                                </label>
                                <label class="color-option">
                                    <input type="radio" name="calendar_color" value="#039be5">
                                    <span class="color-box" style="background: #039be5;"></span>
                                </label>
                                <label class="color-option">
                                    <input type="radio" name="calendar_color" value="#616161">
                                    <span class="color-box" style="background: #616161;"></span>
                                </label>
                                <label class="color-option">
                                    <input type="radio" name="calendar_color" value="#3f51b5">
                                    <span class="color-box" style="background: #3f51b5;"></span>
                                </label>
                                <label class="color-option">
                                    <input type="radio" name="calendar_color" value="#0b8043">
                                    <span class="color-box" style="background: #0b8043;"></span>
                                </label>
                                <label class="color-option">
                                    <input type="radio" name="calendar_color" value="#d50000">
                                    <span class="color-box" style="background: #d50000;"></span>
                                </label>
                                <label class="color-option">
                                    <input type="radio" name="calendar_color" value="#13bfa6">
                                    <span class="color-box" style="background: #13bfa6;"></span>
                                </label>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Description</label>
                            <textarea class="form-control" id="calendarDescription" rows="3"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-sm btn-primary" id="saveCalendarBtn">
                        <i class="fas fa-save me-2"></i>Save
                    </button>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.10/index.global.min.js'></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.13.18/jquery.timepicker.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBfGOjmqKtEBRsfVN9szUo_tac20wcI9HM&libraries=places">
    </script>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // const calendarEl = document.getElementById('calendar');
            // let currentEventId = null;
            // let selectedDates = [];
            // let miniCalendarDate = new Date();
            // let autocomplete;
            // let userCalendars = [];
            // let visibleCalendarIds = [];
            // let selectedCalendarForNewEvent = null;

            const calendarEl = document.getElementById('calendar');
            let currentEventId = null;
            let selectedDates = [];
            let miniCalendarDate = new Date();
            let autocomplete;
            let userCalendars = [];
            let visibleCalendarIds = [];

            // Populate Calendar Dropdown
            function populateCalendarDropdown() {
                const calendarSelect = document.getElementById('calendar_id');
                if (!calendarSelect) return;

                calendarSelect.innerHTML = '<option value="">Select Calendar *</option>';

                if (userCalendars && userCalendars.length > 0) {
                    userCalendars.forEach(cal => {
                        const option = document.createElement('option');
                        option.value = cal.id;
                        option.textContent = cal.name;
                        option.style.color = cal.color;

                        if (cal.is_default) {
                            option.selected = true;
                        }

                        calendarSelect.appendChild(option);
                    });
                } else {
                    calendarSelect.innerHTML = '<option value="">No calendars - Create one first</option>';
                }
            }

            // Load user calendars on page load
            loadUserCalendars();

            // Initialize Google Places Autocomplete
            function initAutocomplete() {
                const input = document.getElementById('location');
                if (autocomplete) {
                    google.maps.event.clearInstanceListeners(input);
                }
                autocomplete = new google.maps.places.Autocomplete(input, {
                    types: ['geocode', 'establishment'],
                    fields: ['formatted_address', 'geometry', 'name']
                });
                autocomplete.addListener('place_changed', function() {
                    const place = autocomplete.getPlace();
                    if (!place.geometry) {
                        showToast('No details available for: ' + place.name, 'error');
                        return;
                    }
                    if (place.geometry) {
                        const lat = place.geometry.location.lat();
                        const lng = place.geometry.location.lng();
                        document.getElementById('latitude').value = lat;
                        document.getElementById('longitude').value = lng;
                        document.getElementById('location').value = place.formatted_address || place.name;
                    }
                });
            }

            function waitForGoogleMaps(callback) {
                if (typeof google !== 'undefined' && google.maps && google.maps.places) {
                    callback();
                } else {
                    setTimeout(() => waitForGoogleMaps(callback), 100);
                }
            }

            waitForGoogleMaps(function() {
                initAutocomplete();
            });

            $('#createWorkModal').on('show.bs.modal', function() {
                populateCalendarDropdown();
            });

            $('#createWorkModal').on('shown.bs.modal', function() {
                setTimeout(function() {
                    waitForGoogleMaps(function() {
                        initAutocomplete();
                    });
                }, 300);
            });

            // Initialize FullCalendar
            const calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'timeGridDay',
                headerToolbar: false,
                editable: true,
                selectable: true,
                selectMirror: true,
                dayMaxEvents: true,
                weekends: true,
                height: '100%',
                allDaySlot: true,
                slotMinTime: '00:00:00',
                slotMaxTime: '24:00:00',
                slotDuration: '00:30:00',
                slotLabelInterval: '01:00',
                scrollTime: '09:00:00',
                nowIndicator: true,
                slotLabelFormat: {
                    hour: 'numeric',
                    minute: '2-digit',
                    omitZeroMinute: false,
                    meridiem: 'short'
                },
                eventTimeFormat: {
                    hour: 'numeric',
                    minute: '2-digit',
                    meridiem: 'short'
                },
                displayEventTime: true,

                // calendar_ids filter added
                events: {
                    url: '{{ route('calendar.events') }}',
                    method: 'GET',
                    extraParams: function() {
                        return {
                            team_id: $('#teamFilter').val(),
                            status: $('#statusFilter').val(),
                            category_id: $('#categoryFilter').val(),
                            calendar_ids: visibleCalendarIds.join(',')
                        };
                    },
                    failure: function() {
                        showToast('Failed to load events', 'error');
                    }
                },

                eventClick: function(info) {
                    info.jsEvent.preventDefault();
                    showEventDetails(info.event);
                },
                select: function(info) {
                    openCreateModal(info.startStr, info.endStr);
                },
                eventDrop: function(info) {
                    updateEventDate(info.event);
                },
                eventResize: function(info) {
                    updateEventDate(info.event);
                },
                datesSet: function(info) {
                    updateCalendarTitle(info.view);
                }
            });

            // Update view switcher buttons
            document.querySelectorAll('.view-btn').forEach(btn => {
                btn.addEventListener('click', function() {
                    document.querySelectorAll('.view-btn').forEach(b => b.classList.remove(
                        'active'));
                    this.classList.add('active');
                    calendar.changeView(this.dataset.view);
                });
            });

            calendar.render();
            renderMiniCalendar();

            // NEW: Load User Calendars
            async function loadUserCalendars() {
                try {
                    const response = await fetch('{{ route('calendars.list') }}');
                    const calendars = await response.json();
                    userCalendars = calendars;
                    visibleCalendarIds = calendars.filter(c => c.is_visible).map(c => c.id);
                    renderCalendarList();
                    populateCalendarDropdown();
                    calendar.refetchEvents(); // Refresh events after loading calendars
                } catch (error) {
                    console.error('Error loading calendars:', error);
                    showToast('Failed to load calendars', 'error');
                }
            }

            // NEW: Render Calendar List
            function renderCalendarList() {
                const container = document.getElementById('calendarListContainer');

                if (userCalendars.length === 0) {
                    container.innerHTML = '<div class="no-calendars">No calendars yet. Create one!</div>';
                    return;
                }

                container.innerHTML = userCalendars.map(cal => `
                <div class="calendar-item" data-calendar-id="${cal.id}">
                    <div class="calendar-checkbox ${cal.is_visible ? 'checked' : ''}"
                        onclick="toggleCalendarVisibility(${cal.id})"
                        style="--cal-color: ${cal.color};">
                        ${cal.is_visible ? '<i class="fas fa-check"></i>' : ''}
                    </div>
                    <div class="calendar-info" onclick="selectCalendar(${cal.id})">
                        <div class="calendar-name" style="color: ${cal.color};">${cal.name}</div>
                        <div class="calendar-count">${cal.event_count || 0} events</div>
                    </div>
                    <div class="calendar-actions">
                        <button class="calendar-menu-btn" onclick="showCalendarMenu(event, ${cal.id})">
                            <i class="fas fa-ellipsis-v"></i>
                        </button>
                    </div>
                </div>
            `).join('');
            }

            // Toggle Calendar Visibility
            window.toggleCalendarVisibility = async function(calendarId) {
                try {
                    const response = await fetch(`/calendars/${calendarId}/toggle`, {
                        method: 'POST',
                        headers: {
                            'X-CSRF-TOKEN': '{{ csrf_token() }}'
                        }
                    });
                    const data = await response.json();

                    if (data.success) {
                        const calIndex = userCalendars.findIndex(c => c.id === calendarId);
                        if (calIndex !== -1) {
                            userCalendars[calIndex].is_visible = data.is_visible;
                            visibleCalendarIds = userCalendars.filter(c => c.is_visible).map(c => c.id);
                            renderCalendarList();
                            calendar.refetchEvents(); // FIXED: Refresh events immediately
                        }
                    }
                } catch (error) {
                    showToast('Failed to toggle calendar', 'error');
                }
            };

            // NEW: Show Calendar Context Menu
            window.showCalendarMenu = function(event, calendarId) {
                event.stopPropagation();
                const cal = userCalendars.find(c => c.id === calendarId);
                if (!cal) return;

                Swal.fire({
                    title: cal.name,
                    html: `
                        <div class="calendar-menu-options" style="height:150px; overflow:auto;">
                            <button class="menu-option btn" onclick="editCalendar(${calendarId})">
                                <i class="fas fa-edit"></i> Edit Calendar
                            </button>
                            ${!cal.is_default ? `
                                                                                                                                                                                                <button class="menu-option btn text-danger" onclick="deleteCalendar(${calendarId})">
                                                                                                                                                                                                    <i class="fas fa-trash"></i> Delete Calendar
                                                                                                                                                                                                </button>
                                                                                                                                                                                            ` : ''}
                        </div>
                    `,
                    showConfirmButton: false,
                    showCloseButton: true,
                    customClass: {
                        popup: 'calendar-menu-popup'
                    }
                });
            };

            // NEW: Open Add Calendar Modal
            window.openAddCalendarModal = function() {
                document.getElementById('calendarModalTitle').innerHTML =
                    '<i class="fas fa-calendar-plus me-2"></i>Add Calendar';
                document.getElementById('calendarForm').reset();
                document.getElementById('calendarId').value = '';
                $('#addCalendarModal').modal('show');
            };

            // NEW: Edit Calendar
            window.editCalendar = function(calendarId) {
                const cal = userCalendars.find(c => c.id === calendarId);
                if (!cal) return;

                Swal.close();
                document.getElementById('calendarModalTitle').innerHTML =
                    '<i class="fas fa-edit me-2"></i>Edit Calendar';
                document.getElementById('calendarId').value = cal.id;
                document.getElementById('calendarName').value = cal.name;
                document.getElementById('calendarDescription').value = cal.description || '';
                document.querySelector(`input[name="calendar_color"][value="${cal.color}"]`).checked = true;
                $('#addCalendarModal').modal('show');
            };


            // Save Calendar Button with Loader
            document.getElementById('saveCalendarBtn').addEventListener('click', async function() {
                const btn = this;
                const calendarId = document.getElementById('calendarId').value;
                const name = document.getElementById('calendarName').value;
                const color = document.querySelector('input[name="calendar_color"]:checked').value;
                const description = document.getElementById('calendarDescription').value;

                if (!name) {
                    showToast('Please enter calendar name', 'error');
                    return;
                }

                const url = calendarId ? `/calendars/${calendarId}` : '/calendars/create';
                const method = calendarId ? 'PUT' : 'POST';

                // Show Loader
                btn.disabled = true;
                btn.innerHTML = '<i class="fas fa-spinner fa-spin me-2"></i>Saving...';

                try {
                    const response = await fetch(url, {
                        method: method,
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRF-TOKEN': '{{ csrf_token() }}'
                        },
                        body: JSON.stringify({
                            name,
                            color,
                            description
                        })
                    });

                    const data = await response.json();

                    if (data.success) {
                        $('#addCalendarModal').modal('hide');
                        showToast(data.message, 'success');
                        await loadUserCalendars();
                    } else {
                        showToast(data.message || 'Failed to save calendar', 'error');
                    }
                } catch (error) {
                    showToast('Failed to save calendar', 'error');
                } finally {
                    btn.disabled = false;
                    btn.innerHTML = '<i class="fas fa-save me-2"></i>Save';
                }
            });

            // NEW: Delete Calendar
            window.deleteCalendar = async function(calendarId) {
                const cal = userCalendars.find(c => c.id === calendarId);
                if (!cal || cal.is_default) return;

                Swal.close();

                const result = await Swal.fire({
                    title: 'Delete Calendar?',
                    text: `All events in "${cal.name}" will also be deleted!`,
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#d33',
                    cancelButtonColor: '#3085d6',
                    confirmButtonText: 'Yes, delete it!'
                });

                if (result.isConfirmed) {
                    try {
                        const response = await fetch(`/calendars/${calendarId}`, {
                            method: 'DELETE',
                            headers: {
                                'X-CSRF-TOKEN': '{{ csrf_token() }}'
                            }
                        });

                        const data = await response.json();

                        if (data.success) {
                            showToast(data.message, 'success');
                            await loadUserCalendars();
                        }
                    } catch (error) {
                        showToast('Failed to delete calendar', 'error');
                    }
                }
            };

            // Update calendar title
            function updateCalendarTitle(view) {
                document.getElementById('calendarTitle').textContent = view.title;
            }

            // Render Mini Calendar
            function renderMiniCalendar() {
                const year = miniCalendarDate.getFullYear();
                const month = miniCalendarDate.getMonth();
                const monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
                    'July', 'August', 'September', 'October', 'November', 'December'
                ];
                document.getElementById('miniCalendarTitle').textContent = `${monthNames[month]} ${year}`;

                const firstDay = new Date(year, month, 1).getDay();
                const daysInMonth = new Date(year, month + 1, 0).getDate();
                const daysInPrevMonth = new Date(year, month, 0).getDate();
                const grid = document.getElementById('miniCalendarGrid');
                grid.innerHTML = '';

                const dayHeaders = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];
                dayHeaders.forEach(day => {
                    const header = document.createElement('div');
                    header.className = 'mini-calendar-day-header';
                    header.textContent = day;
                    grid.appendChild(header);
                });

                for (let i = firstDay - 1; i >= 0; i--) {
                    const day = daysInPrevMonth - i;
                    const dayEl = createMiniCalendarDay(day, year, month - 1, true);
                    grid.appendChild(dayEl);
                }

                const today = new Date();
                for (let day = 1; day <= daysInMonth; day++) {
                    const isToday = day === today.getDate() &&
                        month === today.getMonth() &&
                        year === today.getFullYear();
                    const dayEl = createMiniCalendarDay(day, year, month, false, isToday);
                    grid.appendChild(dayEl);
                }

                const totalCells = firstDay + daysInMonth;
                const remainingCells = 42 - totalCells;
                for (let day = 1; day <= remainingCells; day++) {
                    const dayEl = createMiniCalendarDay(day, year, month + 1, true);
                    grid.appendChild(dayEl);
                }
            }

            let isDragging = false;
            let dragStartDate = null;
            let dragEndDate = null;

            function createMiniCalendarDay(day, year, month, isOtherMonth, isToday = false) {
                const dayEl = document.createElement('div');
                dayEl.className = 'mini-calendar-day';
                if (isOtherMonth) dayEl.classList.add('other-month');
                if (isToday) dayEl.classList.add('today');
                dayEl.textContent = day;
                const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
                dayEl.dataset.date = dateStr;

                dayEl.addEventListener('mousedown', function(e) {
                    e.preventDefault();
                    isDragging = true;
                    dragStartDate = dateStr;
                    dragEndDate = dateStr;
                    selectedDates = [dateStr];
                    updateSelectedDates();
                });

                dayEl.addEventListener('mouseenter', function() {
                    if (isDragging && dragStartDate) {
                        dragEndDate = dateStr;
                        selectedDates = getDateRange(dragStartDate, dragEndDate);
                        updateSelectedDates();
                    }
                });

                dayEl.addEventListener('mouseup', function() {
                    if (isDragging) {
                        isDragging = false;
                        dragEndDate = dateStr;
                        selectedDates = getDateRange(dragStartDate, dragEndDate);
                        updateSelectedDates();
                        filterCalendarByDates();
                    }
                });

                dayEl.addEventListener('click', function(e) {
                    if (!isDragging) {
                        document.querySelectorAll('.mini-calendar-day.selected').forEach(el => el.classList
                            .remove('selected'));
                        selectedDates = [dateStr];
                        updateSelectedDates();
                        filterCalendarByDates();
                    }
                });

                return dayEl;
            }

            function updateSelectedDates() {
                document.querySelectorAll('.mini-calendar-day').forEach(el => {
                    el.classList.toggle('selected', selectedDates.includes(el.dataset.date));
                });
            }

            function getDateRange(start, end) {
                const range = [];
                const startDate = new Date(start);
                const endDate = new Date(end);
                const step = startDate <= endDate ? 1 : -1;
                for (let d = new Date(startDate);
                    (step === 1 ? d <= endDate : d >= endDate); d.setDate(d.getDate() + step)) {
                    const formatted = d.toISOString().split('T')[0];
                    range.push(formatted);
                }
                return range;
            }

            document.addEventListener('mouseup', () => {
                isDragging = false;
            });

            function filterCalendarByDates() {
                if (selectedDates.length === 0) return;
                selectedDates.sort();
                const startDate = selectedDates[0];
                const endDate = selectedDates[selectedDates.length - 1];
                calendar.gotoDate(startDate);

                if (selectedDates.length === 1) {
                    calendar.changeView('dayGridDay', startDate);
                } else {
                    const daysDiff = Math.ceil((new Date(endDate) - new Date(startDate)) / (1000 * 60 * 60 * 24));
                    if (daysDiff <= 7) {
                        calendar.changeView('timeGridWeek', startDate);
                    } else {
                        calendar.changeView('dayGridMonth', startDate);
                    }
                }
            }

            document.getElementById('miniPrevMonth').addEventListener('click', function() {
                miniCalendarDate.setMonth(miniCalendarDate.getMonth() - 1);
                renderMiniCalendar();
            });

            document.getElementById('miniNextMonth').addEventListener('click', function() {
                miniCalendarDate.setMonth(miniCalendarDate.getMonth() + 1);
                renderMiniCalendar();
            });

            document.getElementById('todayBtn').addEventListener('click', function() {
                calendar.today();
                miniCalendarDate = new Date();
                selectedDates = [new Date().toISOString().split('T')[0]];
                renderMiniCalendar();
                const todayStr = new Date().toISOString().split('T')[0];
                const todayEl = document.querySelector(`.mini-calendar-day[data-date="${todayStr}"]`);
                if (todayEl) {
                    todayEl.classList.add('selected');
                }
            });

            document.getElementById('prevBtn').addEventListener('click', function() {
                calendar.prev();
            });

            document.getElementById('nextBtn').addEventListener('click', function() {
                calendar.next();
            });

            document.querySelectorAll('.view-btn').forEach(btn => {
                btn.addEventListener('click', function() {
                    document.querySelectorAll('.view-btn').forEach(b => b.classList.remove(
                        'active'));
                    this.classList.add('active');
                    calendar.changeView(this.dataset.view);
                });
            });

            $('#teamFilter, #statusFilter, #categoryFilter').on('change', function() {
                calendar.refetchEvents();
            });

            function openCreateModal(date = null) {
                $('#modalTitle').html('<i class="fas fa-calendar-plus me-2"></i>Create New Work Schedule');
                $('#workForm')[0].reset();
                $('#workId').val('');
                $('#formMethod').val('POST');
                $('#latitude').val('');
                $('#longitude').val('');
                $('.error-text').text('');

                if (date) {
                    $('#work_date').val(date);
                } else {
                    $('#work_date').val(new Date().toISOString().split('T')[0]);
                }

                $('#start_time').val('09:00 AM');
                $('#end_time').val('05:00 PM');
                $('#start_time_wrapper, #end_time_wrapper').show();
                $('#start_time, #end_time').prop('disabled', false);
                $('#is_all_day').prop('checked', false);
                $('#createWorkModal').modal('show');
            }

            function showEventDetails(event) {
                currentEventId = event.id;
                const props = event.extendedProps;
                const startDate = new Date(event.start);
                const endDate = event.end ? new Date(event.end) : startDate;

                const statusBadge = props.completed ?
                    '<span class="badge bg-success">Completed</span>' :
                    (props.rescheduled ? '<span class="badge bg-warning">Rescheduled</span>' :
                        '<span class="badge bg-primary">Pending</span>');

                let dateTimeDisplay = '';
                if (props.is_all_day) {
                    dateTimeDisplay = `
                        <i class="far fa-calendar" style="margin-right: 8px;"></i>
                        ${startDate.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
                        ${endDate.getDate() !== startDate.getDate() ? ' - ' + endDate.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }) : ''}
                        <span class="badge bg-info ms-2">All Day</span>
                    `;
                } else {
                    dateTimeDisplay = `
                        <i class="far fa-calendar" style="margin-right: 8px;"></i>
                        ${startDate.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
                        <br>
                        <i class="far fa-clock" style="margin-right: 8px;"></i>
                        ${startDate.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })} -
                        ${endDate.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}
                    `;
                }

                let detailsHtml = `
                    <div style="padding: 8px 0;">
                        <div style="margin-bottom: 16px;">
                            <strong style="color: #5f6368; font-size: 12px;">TITLE</strong>
                            <div style="font-size: 16px; color: #3c4043; margin-top: 4px;">${event.title}</div>
                        </div>
                        <div style="margin-bottom: 16px;">
                            <strong style="color: #5f6368; font-size: 12px;">DATE & TIME</strong>
                            <div style="font-size: 14px; color: #3c4043; margin-top: 4px;">${dateTimeDisplay}</div>
                        </div>
                        <div style="margin-bottom: 16px;">
                            <strong style="color: #5f6368; font-size: 12px;">STATUS</strong>
                            <div style="margin-top: 4px;">${statusBadge}</div>
                        </div>
                `;

                if (props.calendar_name) {
                    detailsHtml += `
                        <div style="margin-bottom: 16px;">
                            <strong style="color: #5f6368; font-size: 12px;">CALENDAR</strong>
                            <div style="font-size: 14px; color: ${event.backgroundColor}; margin-top: 4px;">
                                <i class="fas fa-calendar" style="margin-right: 8px;"></i>
                                ${props.calendar_name}
                            </div>
                        </div>
                    `;
                }

                if (event.extendedProps.description) {
                    detailsHtml += `
                        <div style="margin-bottom: 16px;">
                            <strong style="color: #5f6368; font-size: 12px;">DESCRIPTION</strong>
                            <div style="font-size: 14px; color: #3c4043; margin-top: 4px;">${event.extendedProps.description}</div>
                        </div>
                    `;
                }

                if (event.extendedProps.location) {
                    const lat = props.latitude;
                    const lng = props.longitude;
                    const mapsUrl = lat && lng ?
                        `https://www.google.com/maps/search/?api=1&query=${lat},${lng}` :
                        `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(event.extendedProps.location)}`;
                    detailsHtml += `
                        <div style="margin-bottom: 16px;">
                            <strong style="color: #5f6368; font-size: 12px;">LOCATION</strong>
                            <div style="font-size: 14px; color: #3c4043; margin-top: 4px;">
                                <i class="fas fa-map-marker-alt" style="margin-right: 8px;"></i>
                                <a href="${mapsUrl}" target="_blank" style="color: #1a73e8; text-decoration: none;">
                                    ${event.extendedProps.location}
                                    <i class="fas fa-external-link-alt" style="font-size: 12px; margin-left: 4px;"></i>
                                </a>
                            </div>
                        </div>
                    `;
                }

                if (props.team) {
                    detailsHtml += `
                        <div style="margin-bottom: 16px;">
                            <strong style="color: #5f6368; font-size: 12px;">TEAM</strong>
                            <div style="font-size: 14px; color: #3c4043; margin-top: 4px;">
                                <i class="fas fa-users" style="margin-right: 8px;"></i>
                                ${props.team}
                            </div>
                        </div>
                    `;
                }

                if (props.category) {
                    detailsHtml += `
                        <div style="margin-bottom: 16px;">
                            <strong style="color: #5f6368; font-size: 12px;">CATEGORY</strong>
                            <div style="font-size: 14px; color: #3c4043; margin-top: 4px;">
                                <i class="fas fa-tag" style="margin-right: 8px;"></i>
                                ${props.category}
                            </div>
                        </div>
                    `;
                }

                if (props.note) {
                    detailsHtml += `
                        <div style="margin-bottom: 16px;">
                            <strong style="color: #5f6368; font-size: 12px;">NOTE</strong>
                            <div style="font-size: 14px; color: #3c4043; margin-top: 4px;">${props.note}</div>
                        </div>
                    `;
                }

                detailsHtml += '</div>';
                $('#eventDetailsContent').html(detailsHtml);
                $('#viewEventModal').modal('show');
            }

            $('#editEventBtn').on('click', function() {
                $('#viewEventModal').modal('hide');
                loadEventForEdit(currentEventId);
            });

            function loadEventForEdit(eventId) {
                $.ajax({
                    url: `/calendar/${eventId}`,
                    method: 'GET',
                    success: function(work) {
                        $('#modalTitle').html('<i class="fas fa-edit me-2"></i>Edit Work Schedule');
                        $('#workId').val(work.id);
                        $('#formMethod').val('PUT');
                        $('#title').val(work.title);
                        $('#description').val(work.description);
                        $('#location').val(work.location);
                        $('#latitude').val(work.latitude);
                        $('#longitude').val(work.longitude);
                        $('#team_id').val(work.team_id);
                        $('#category_id').val(work.category_id);
                        $('#note').val(work.note);

                        const startDateTime = new Date(work.start_datetime);
                        const endDateTime = new Date(work.end_datetime);
                        const workDate = startDateTime.toISOString().split('T')[0];
                        $('#work_date').val(workDate);

                        if (work.is_all_day) {
                            $('#is_all_day').prop('checked', true);
                            $('#start_time_wrapper, #end_time_wrapper').hide();
                            $('#start_time, #end_time').prop('disabled', true).prop('required', false)
                                .val('');
                        } else {
                            $('#is_all_day').prop('checked', false);
                            $('#start_time_wrapper, #end_time_wrapper').show();
                            $('#start_time, #end_time').prop('disabled', false).prop('required', true);
                            const startTime = formatTime12Hour(startDateTime);
                            const endTime = formatTime12Hour(endDateTime);
                            $('#start_time').val(startTime);
                            $('#end_time').val(endTime);
                            $('#start_time, #end_time').timepicker('setTime', null);
                            $('#start_time').timepicker('setTime', startTime);
                            $('#end_time').timepicker('setTime', endTime);
                        }

                        $('#createWorkModal').modal('show');
                    },
                    error: function(xhr) {
                        console.error('Error loading work:', xhr);
                        showToast('Failed to load work details', 'error');
                    }
                });
            }

            $('#saveWorkBtn').on('click', function(e) {
                e.preventDefault();
                let formData = new FormData($('#workForm')[0]);
                let id = $('#workId').val();
                let url = id ? "{{ route('calendar.update', ':id') }}".replace(':id', id) :
                    "{{ route('calendar.store') }}";

                if (id) {
                    formData.append('_method', 'POST');
                }

                const isAllDay = $('#is_all_day').is(':checked');
                formData.set('is_all_day', isAllDay ? '1' : '0');

                if (isAllDay) {
                    formData.delete('start_time');
                    formData.delete('end_time');
                }

                // NEW: Add selected calendar if creating new event
                if (!id && selectedCalendarForNewEvent) {
                    formData.append('calendar_id', selectedCalendarForNewEvent);
                }

                $.ajax({
                    url: url,
                    type: 'POST',
                    data: formData,
                    contentType: false,
                    processData: false,
                    headers: {
                        'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    },
                    beforeSend: function() {
                        $('.error-text').text('');
                        $('#saveWorkBtn').prop('disabled', true).html(
                            '<i class="fas fa-spinner fa-spin me-2"></i>Processing...');
                    },
                    success: function(response) {
                        if (response.status === false) {
                            $.each(response.errors, function(field, messages) {
                                $('.' + field + '_error').text(messages[0]);
                            });
                            $('#saveWorkBtn').prop('disabled', false).html(
                                '<i class="fas fa-save me-2"></i>Save');
                        } else {
                            $('#createWorkModal').modal('hide');
                            $('#workForm')[0].reset();
                            calendar.refetchEvents();
                            loadUserCalendars(); // Refresh calendar list to update event counts
                            showToast(response.message || 'Work saved successfully!',
                                'success');
                            $('#saveWorkBtn').prop('disabled', false).html(
                                '<i class="fas fa-save me-2"></i>Save');
                        }
                    },
                    error: function(xhr) {
                        $('#saveWorkBtn').prop('disabled', false).html(
                            '<i class="fas fa-save me-2"></i>Save');
                        if (xhr.status === 422) {
                            const errors = xhr.responseJSON.errors;
                            $.each(errors, function(field, messages) {
                                const fieldName = field.replace(/\./g, '_');
                                $('.' + fieldName + '_error').text(messages[0]);
                            });
                            showToast('Please fix the validation errors', 'error');
                        } else {
                            showToast(xhr.responseJSON?.message || 'Failed to save work',
                                'error');
                        }
                    }
                });
            });

            $('#createWorkModal').on('hidden.bs.modal', function() {
                $('#workForm')[0].reset();
                $('.error-text').text('');
                $('#workId').val('');
                $('#formMethod').val('POST');
                $('#start_time_wrapper, #end_time_wrapper').show();
                $('#start_time, #end_time').prop('disabled', false);
                $('#is_all_day').prop('checked', false);
            });

            $('#deleteEventBtn').on('click', function(e) {
                e.preventDefault();
                showDeleteConfirm(currentEventId);
            });

            function showDeleteConfirm(id) {
                Swal.fire({
                    title: 'Are you sure you want to delete this work?',
                    text: 'If you delete this, it will be gone forever.',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!',
                    cancelButtonText: 'Cancel'
                }).then((result) => {
                    if (result.isConfirmed) {
                        deleteItem(id);
                    }
                });
            }

            function deleteItem(id) {
                $.ajax({
                    url: `/calendar/${id}`,
                    method: 'DELETE',
                    data: {
                        _token: '{{ csrf_token() }}'
                    },
                    beforeSend: function() {
                        Swal.fire({
                            title: 'Deleting...',
                            text: 'Please wait while we remove the work.',
                            allowOutsideClick: false,
                            didOpen: () => Swal.showLoading()
                        });
                    },
                    success: function(response) {
                        Swal.close();
                        $('#viewEventModal').modal('hide');
                        calendar.refetchEvents();
                        loadUserCalendars(); // Refresh calendar list
                        showToast(response.message, 'success');
                    },
                    error: function() {
                        Swal.close();
                        showToast('Failed to delete work', 'error');
                    }
                });
            }

            function updateEventDate(event) {
                const startDate = new Date(event.start);
                const formData = {
                    _token: '{{ csrf_token() }}',
                    _method: 'POST',
                    title: event.title,
                    work_date: startDate.toISOString().split('T')[0],
                    time: startDate.toTimeString().split(' ')[0]
                };

                $.ajax({
                    url: `/calendar/${event.id}`,
                    method: 'POST',
                    data: formData,
                    success: function(response) {
                        showToast('Event updated successfully', 'success');
                    },
                    error: function() {
                        showToast('Failed to update event', 'error');
                        calendar.refetchEvents();
                    }
                });
            }

            // Sync Button - Use Full Sync
            $('#syncGoogleBtn').on('click', function() {
                const btn = $(this);
                btn.prop('disabled', true).html('<i class="fas fa-spinner fa-spin"></i> Syncing...');

                $.ajax({
                    url: '{{ route('google.full.sync') }}', // CHANGED: Use full sync
                    method: 'POST',
                    data: {
                        _token: '{{ csrf_token() }}'
                    },
                    success: function(response) {
                        if (response.success) {
                            showToast(response.message, 'success');
                            loadUserCalendars();
                            calendar.refetchEvents();
                        } else {
                            showToast(response.message, 'error');
                        }
                    },
                    error: function(xhr) {
                        showToast(xhr.responseJSON?.message || 'Sync failed', 'error');
                    },
                    complete: function() {
                        btn.prop('disabled', false).html(
                        '<i class="fas fa-sync"></i> Sync All');
                    }
                });
            });

            function showToast(message, type = 'info') {
                const toast = $(`
                    <div class="toast-notification ${type}">
                        <i class="fas fa-${type === 'success' ? 'check-circle' : type === 'error' ? 'exclamation-circle' : 'info-circle'}" style="color: ${type === 'success' ? '#34a853' : type === 'error' ? '#ea4335' : '#4285f4'}"></i>
                        <span style="color: #3c4043; font-size: 14px;">${message}</span>
                    </div>
                `);
                $('body').append(toast);
                setTimeout(() => {
                    toast.fadeOut(300, function() {
                        $(this).remove();
                    });
                }, 3000);
            }

            @if (session('success'))
                showToast('{{ session('success') }}', 'success');
            @endif

            @if (session('error'))
                showToast('{{ session('error') }}', 'error');
            @endif

            const todayStr = new Date().toISOString().split('T')[0];
            selectedDates = [todayStr];
            setTimeout(() => {
                const todayEl = document.querySelector(`.mini-calendar-day[data-date="${todayStr}"]`);
                if (todayEl) {
                    todayEl.classList.add('selected');
                }
            }, 100);

            $('.timepicker').timepicker({
                timeFormat: 'h:i A',
                interval: 15,
                dynamic: false,
                dropdown: true,
                scrollbar: true,
                startTime: '12:00 AM',
                endTime: '11:45 PM'
            });

            $('#is_all_day').on('change', function() {
                if ($(this).is(':checked')) {
                    $('#start_time, #end_time').prop('disabled', true).val('');
                    $('#start_time_wrapper, #end_time_wrapper').hide();
                } else {
                    $('#start_time, #end_time').prop('disabled', false);
                    $('#start_time_wrapper, #end_time_wrapper').show();
                }
            });
        });

        function formatTime12Hour(date) {
            let hours = date.getHours();
            let minutes = date.getMinutes();
            let ampm = hours >= 12 ? 'PM' : 'AM';
            hours = hours % 12;
            hours = hours ? hours : 12;
            minutes = minutes < 10 ? '0' + minutes : minutes;
            return hours + ':' + minutes + ' ' + ampm;
        }
    </script>


    <script>
        // Print Calendar Function
        document.getElementById('printCalendarBtn').addEventListener('click', function() {
            printCalendar();
        });

        function printCalendar() {
            // Get current view info
            const currentView = calendar.view;
            const viewTitle = currentView.title;
            const viewType = currentView.type;

            // Get all visible events
            const events = calendar.getEvents();

            // Create print window
            const printWindow = window.open('', '_blank', 'width=900,height=650');

            // Generate print HTML
            let printHTML = `
        <!DOCTYPE html>
        <html>
        <head>
            <title>Calendar - ${viewTitle}</title>
            <style>
                * {
                    margin: 0;
                    padding: 0;
                    box-sizing: border-box;
                }
                body {
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                    padding: 30px;
                    background: white;
                }
                .print-header {
                    text-align: center;
                    margin-bottom: 30px;
                    border-bottom: 3px solid #13bfa6;
                    padding-bottom: 20px;
                }
                .print-header h1 {
                    color: #2c3e50;
                    font-size: 28px;
                    margin-bottom: 10px;
                }
                .print-header p {
                    color: #7f8c8d;
                    font-size: 14px;
                }
                .events-container {
                    margin-top: 20px;
                }
                .date-group {
                    margin-bottom: 30px;
                    page-break-inside: avoid;
                }
                .date-header {
                    background: #13bfa6;
                    color: white;
                    padding: 12px 20px;
                    border-radius: 8px;
                    font-size: 18px;
                    font-weight: 600;
                    margin-bottom: 15px;
                }
                .event-card {
                    border: 1px solid #e0e0e0;
                    border-left: 4px solid;
                    padding: 15px 20px;
                    margin-bottom: 12px;
                    border-radius: 6px;
                    background: #fafafa;
                    page-break-inside: avoid;
                }
                .event-title {
                    font-size: 16px;
                    font-weight: 600;
                    color: #2c3e50;
                    margin-bottom: 8px;
                }
                .event-time {
                    font-size: 14px;
                    color: #555;
                    margin-bottom: 6px;
                }
                .event-time i {
                    margin-right: 6px;
                    color: #13bfa6;
                }
                .event-details {
                    font-size: 13px;
                    color: #666;
                    line-height: 1.6;
                }
                .event-details div {
                    margin-bottom: 4px;
                }
                .event-details i {
                    margin-right: 8px;
                    color: #13bfa6;
                    width: 16px;
                    display: inline-block;
                }
                .no-events {
                    text-align: center;
                    color: #999;
                    padding: 40px;
                    font-style: italic;
                }
                .print-footer {
                    margin-top: 40px;
                    text-align: center;
                    color: #999;
                    font-size: 12px;
                    border-top: 1px solid #e0e0e0;
                    padding-top: 20px;
                }
                @media print {
                    body { padding: 20px; }
                    .print-footer { page-break-before: avoid; }
                }
            </style>
        </head>
        <body>
            <div class="print-header">
                <h1>📅 Work Calendar</h1>
                <p>${viewTitle}</p>
                <p style="margin-top: 5px; font-size: 12px;">Printed on: ${new Date().toLocaleString()}</p>
            </div>
            <div class="events-container">
    `;

            if (events.length === 0) {
                printHTML += '<div class="no-events">No events found for this period</div>';
            } else {
                // Group events by date
                const eventsByDate = {};

                events.forEach(event => {
                    const dateKey = event.start.toLocaleDateString('en-US', {
                        weekday: 'long',
                        year: 'numeric',
                        month: 'long',
                        day: 'numeric'
                    });

                    if (!eventsByDate[dateKey]) {
                        eventsByDate[dateKey] = [];
                    }

                    eventsByDate[dateKey].push(event);
                });

                // Sort dates
                const sortedDates = Object.keys(eventsByDate).sort((a, b) => {
                    return new Date(a) - new Date(b);
                });

                // Generate HTML for each date
                sortedDates.forEach(dateKey => {
                    printHTML += `<div class="date-group">`;
                    printHTML += `<div class="date-header">${dateKey}</div>`;

                    // Sort events by time
                    eventsByDate[dateKey].sort((a, b) => a.start - b.start);

                    eventsByDate[dateKey].forEach(event => {
                        const props = event.extendedProps;
                        const color = event.backgroundColor || '#3b82f6';

                        let timeDisplay = '';
                        if (props.is_all_day) {
                            timeDisplay = '<i class="fas fa-calendar-day"></i>All Day Event';
                        } else {
                            const startTime = event.start.toLocaleTimeString('en-US', {
                                hour: '2-digit',
                                minute: '2-digit'
                            });
                            const endTime = event.end ? event.end.toLocaleTimeString('en-US', {
                                hour: '2-digit',
                                minute: '2-digit'
                            }) : '';
                            timeDisplay =
                                `<i class="fas fa-clock"></i>${startTime}${endTime ? ' - ' + endTime : ''}`;
                        }

                        printHTML += `
                    <div class="event-card" style="border-left-color: ${color};">
                        <div class="event-title">${event.title}</div>
                        <div class="event-time">${timeDisplay}</div>
                        <div class="event-details">
                `;

                        if (event.extendedProps.description) {
                            printHTML +=
                                `<div><i class="fas fa-align-left"></i>${event.extendedProps.description}</div>`;
                        }

                        if (event.extendedProps.location) {
                            printHTML +=
                                `<div><i class="fas fa-map-marker-alt"></i>${event.extendedProps.location}</div>`;
                        }

                        if (props.team) {
                            printHTML += `<div><i class="fas fa-users"></i>Team: ${props.team}</div>`;
                        }

                        if (props.category) {
                            printHTML += `<div><i class="fas fa-tag"></i>Category: ${props.category}</div>`;
                        }

                        if (props.calendar_name) {
                            printHTML +=
                                `<div><i class="fas fa-calendar"></i>Calendar: ${props.calendar_name}</div>`;
                        }

                        // Status badge
                        let statusText = 'Pending';
                        if (props.completed) statusText = '✓ Completed';
                        else if (props.rescheduled) statusText = '↻ Rescheduled';

                        printHTML += `<div><i class="fas fa-info-circle"></i>Status: ${statusText}</div>`;

                        if (props.note) {
                            printHTML += `<div><i class="fas fa-sticky-note"></i>Note: ${props.note}</div>`;
                        }

                        printHTML += `
                        </div>
                    </div>
                `;
                    });

                    printHTML += `</div>`;
                });
            }

            printHTML += `
            </div>
            <div class="print-footer">
                <p>Generated from Work Calendar Management System</p>
                <p>© ${new Date().getFullYear()} - All Rights Reserved</p>
            </div>
        </body>
        </html>
    `;

            // Write to print window
            printWindow.document.open();
            printWindow.document.write(printHTML);
            printWindow.document.close();

            // Wait for content to load, then print
            printWindow.onload = function() {
                setTimeout(() => {
                    printWindow.print();
                    // Close window after printing (optional)
                    printWindow.onafterprint = function() {
                        printWindow.close();
                    };
                }, 250);
            };
        }
    </script>
@endpush

@push('styles')
    <link href='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.10/index.global.min.css' rel='stylesheet' />
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.13.18/jquery.timepicker.min.css">

    <style>
        :root {
            --google-blue: #13bfa6;
            --google-blue-hover: #13bfa6;
            --border-color: #dadce0;
            --sidebar-bg: #ffffff;
            --hover-bg: #f1f3f4;
            --selected-bg: #e8f0fe;
        }

        .calendar-container {
            display: flex;
            height: calc(100vh - 120px);
            background: #fff;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12);
            margin-bottom: 20px;
        }

        .calendar-sidebar {
            width: 280px;
            border-right: 1px solid var(--border-color);
            display: flex;
            flex-direction: column;
            background: var(--sidebar-bg);
            overflow-y: auto;
        }

        .sidebar-header {
            padding: 13px 20px;
            border-bottom: 1px solid var(--border-color);
        }

        .create-btn {
            display: flex;
            align-items: center;
            gap: 12px;
            padding: 12px 24px;
            background: var(--google-blue);
            color: white;
            border: none;
            border-radius: 24px;
            font-size: 14px;
            font-weight: 500;
            cursor: pointer;
            transition: all 0.2s;
            box-shadow: 0 1px 2px rgba(0, 0, 0, 0.3);
            width: 100%;
            justify-content: center;
        }

        .create-btn:hover {
            background: var(--google-blue-hover);
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
        }

        .create-btn i {
            font-size: 18px;
        }

        /* Mini Calendar */
        .mini-calendar {
            padding: 8px 12px;
            flex-shrink: 0;
            border-bottom: 1px solid var(--border-color);
        }

        .mini-calendar-header {
            display: flex;
            align-items: center;
            justify-content: space-between;
            margin-bottom: 12px;
            padding: 0 8px;
        }

        .mini-calendar-title {
            font-size: 14px;
            font-weight: 500;
            color: #3c4043;
        }

        .mini-nav-btn {
            background: none;
            border: none;
            width: 32px;
            height: 32px;
            border-radius: 50%;
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #5f6368;
            transition: background 0.2s;
        }

        .mini-nav-btn:hover {
            background: var(--hover-bg);
        }

        .mini-calendar-grid {
            display: grid;
            grid-template-columns: repeat(7, 1fr);
            gap: 2px;
        }

        .mini-calendar-day-header {
            text-align: center;
            font-size: 11px;
            font-weight: 500;
            color: #70757a;
            padding: 4px 0;
        }

        .mini-calendar-day {
            aspect-ratio: 1;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 12px;
            border-radius: 50%;
            cursor: pointer;
            color: #3c4043;
            transition: all 0.2s;
            user-select: none;
        }

        .mini-calendar-day:hover {
            background: var(--hover-bg);
        }

        .mini-calendar-day.other-month {
            color: #9aa0a6;
        }

        .mini-calendar-day.today {
            background: var(--google-blue);
            color: white;
            font-weight: 600;
        }

        .mini-calendar-day.selected {
            background: var(--selected-bg);
            color: var(--google-blue);
            font-weight: 600;
        }

        /* MY CALENDARS SECTION - NEW */
        .my-calendars-section {
            padding: 5px;
            border-bottom: 1px solid var(--border-color);
            flex-shrink: 0;
        }

        .calendars-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 12px;
        }

        .calendars-title {
            font-size: 14px;
            font-weight: 500;
            color: #3c4043;
        }

        .add-calendar-btn {
            background: none;
            border: none;
            color: #5f6368;
            cursor: pointer;
            padding: 4px 8px;
            border-radius: 4px;
            transition: background 0.2s;
        }

        .add-calendar-btn:hover {
            background: var(--hover-bg);
        }

        .calendar-list-container {
            max-height: 200px;
            overflow-y: auto;
        }

        .loading-calendars,
        .error-message,
        .no-calendars {
            text-align: center;
            padding: 20px;
            color: #5f6368;
            font-size: 13px;
        }

        .calendar-item {
            display: flex;
            align-items: center;
            gap: 10px;
            padding: 8px;
            border-radius: 6px;
            cursor: pointer;
            transition: background 0.2s;
            margin-bottom: 4px;
        }

        .calendar-item:hover {
            background: var(--hover-bg);
        }

        .calendar-checkbox {
            width: 18px;
            height: 18px;
            border: 2px solid #dadce0;
            border-radius: 3px;
            cursor: pointer;
            position: relative;
            transition: all 0.2s;
            flex-shrink: 0;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .calendar-checkbox.checked {
            background: var(--cal-color);
            border-color: var(--cal-color);
        }

        .calendar-checkbox i {
            color: white;
            font-size: 10px;
        }

        .calendar-info {
            flex: 1;
            min-width: 0;
        }

        .calendar-name {
            font-size: 14px;
            font-weight: 500;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }

        .calendar-count {
            font-size: 11px;
            color: #5f6368;
        }

        .calendar-actions {
            flex-shrink: 0;
        }

        .calendar-menu-btn {
            opacity: 0;
            background: none;
            border: none;
            color: #5f6368;
            cursor: pointer;
            padding: 4px;
            border-radius: 4px;
            transition: all 0.2s;
        }

        .calendar-item:hover .calendar-menu-btn {
            opacity: 1;
        }

        .calendar-menu-btn:hover {
            background: #e8eaed;
        }

        /* Color Picker for Calendar Modal */
        .color-picker-grid {
            display: grid;
            grid-template-columns: repeat(6, 1fr);
            gap: 10px;
        }

        .color-option {
            cursor: pointer;
        }

        .color-option input[type="radio"] {
            display: none;
        }

        .color-box {
            display: block;
            width: 40px;
            height: 40px;
            border-radius: 50%;
            border: 3px solid transparent;
            transition: all 0.2s;
        }

        .color-option input[type="radio"]:checked+.color-box {
            border-color: #3c4043;
            transform: scale(1.1);
        }

        .color-option:hover .color-box {
            transform: scale(1.05);
        }

        /* Calendar Menu Popup */
        .calendar-menu-popup {
            width: 300px;
        }

        .calendar-menu-options {
            display: flex;
            flex-direction: column;
            gap: 8px;
        }

        .menu-option {
            width: 100%;
            padding: 12px 16px;
            background: white;
            border: 1px solid var(--border-color);
            border-radius: 4px;
            text-align: left;
            cursor: pointer;
            transition: background 0.2s;
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .menu-option:hover {
            background: var(--hover-bg);
        }

        .menu-option.text-danger {
            color: #d33;
        }

        /* Filters Section */
        .sidebar-filters {
            padding: 16px 0;
            border-top: 1px solid var(--border-color);
            overflow-y: auto;
            flex: 1;
        }

        .filter-group {
            margin-bottom: 20px;
        }

        .filter-label {
            font-size: 14px;
            font-weight: 500;
            color: #3c4043;
            margin-bottom: 8px;
            display: block;
        }

        .filter-select {
            width: 100%;
            padding: 8px 12px;
            border: 1px solid var(--border-color);
            border-radius: 4px;
            font-size: 14px;
            color: #3c4043;
            background: white;
            cursor: pointer;
            transition: all 0.2s;
        }

        .filter-select:focus {
            outline: none;
            border-color: var(--google-blue);
            box-shadow: 0 0 0 2px rgba(26, 115, 232, 0.1);
        }

        .google-sync-section {
            padding: 12px;
            background: #f8f9fa;
            border-radius: 8px;
            margin-top: 16px;
        }

        .sync-status {
            display: flex;
            align-items: center;
            gap: 8px;
            font-size: 13px;
            color: #5f6368;
            margin-bottom: 12px;
        }

        .status-badge {
            display: inline-flex;
            align-items: center;
            gap: 4px;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 12px;
            font-weight: 500;
        }

        .status-badge.connected {
            background: #e6f4ea;
            color: #137333;
        }

        .status-badge.disconnected {
            background: #fce8e6;
            color: #c5221f;
        }

        .sync-actions {
            display: flex;
            gap: 8px;
        }

        .sync-btn {
            flex: 1;
            padding: 8px 12px;
            border-radius: 4px;
            font-size: 13px;
            font-weight: 500;
            border: 1px solid var(--border-color);
            background: white;
            cursor: pointer;
            transition: all 0.2s;
        }

        .sync-btn:hover {
            background: var(--hover-bg);
        }

        .sync-btn.primary {
            background: var(--google-blue);
            color: white;
            border: none;
        }

        .sync-btn.primary:hover {
            background: var(--google-blue-hover);
        }

        /* Main Calendar Area */
        .calendar-main {
            flex: 1;
            display: flex;
            flex-direction: column;
            overflow: hidden;
        }

        .calendar-header {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 16px 20px;
            border-bottom: 1px solid var(--border-color);
            background: white;
        }

        .calendar-header-left {
            display: flex;
            align-items: center;
            gap: 16px;
        }

        .today-btn {
            padding: 8px 16px;
            border: 1px solid var(--border-color);
            border-radius: 4px;
            background: white;
            color: #3c4043;
            font-size: 14px;
            font-weight: 500;
            cursor: pointer;
            transition: all 0.2s;
        }

        .today-btn:hover {
            background: var(--hover-bg);
        }

        .calendar-nav {
            display: flex;
            gap: 4px;
        }

        .nav-btn {
            width: 36px;
            height: 36px;
            border: none;
            background: none;
            border-radius: 50%;
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #5f6368;
            transition: background 0.2s;
        }

        .nav-btn:hover {
            background: var(--hover-bg);
        }

        .calendar-title {
            font-size: 22px;
            font-weight: 400;
            color: #3c4043;
            margin-left: 16px;
        }

        .calendar-header-right {
            display: flex;
            align-items: center;
            gap: 8px;
        }

        .view-switcher {
            display: flex;
            border: 1px solid var(--border-color);
            border-radius: 4px;
            overflow: hidden;
        }

        .view-btn {
            padding: 8px 16px;
            border: none;
            background: white;
            color: #5f6368;
            font-size: 14px;
            font-weight: 500;
            cursor: pointer;
            transition: all 0.2s;
            border-right: 1px solid var(--border-color);
        }

        .view-btn:last-child {
            border-right: none;
        }

        .view-btn:hover {
            background: var(--hover-bg);
        }

        .view-btn.active {
            background: var(--selected-bg);
            color: var(--google-blue);
        }

        .calendar-content {
            flex: 1;
            overflow: auto;
            background: #fff;
        }

        /* FullCalendar Custom Styles */
        .fc {
            font-family: 'Google Sans', 'Roboto', Arial, sans-serif;
        }

        .fc .fc-toolbar {
            display: none;
        }

        .fc-theme-standard td,
        .fc-theme-standard th {
            border-color: var(--border-color);
        }

        .fc-col-header-cell {
            padding: 12px 4px;
            font-size: 11px;
            font-weight: 500;
            color: #70757a;
            text-transform: uppercase;
            background: #fff;
        }

        .fc-daygrid-day-number {
            color: #3c4043;
            font-size: 12px;
            padding: 8px;
        }

        .fc-day-today {
            background-color: #e8f0fe !important;
        }

        .fc-day-today .fc-daygrid-day-number {
            background: var(--google-blue);
            color: white;
            width: 28px;
            height: 28px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: 600;
        }

        .fc-event {
            border: none !important;
            border-radius: 4px;
            padding: 2px 6px;
            font-size: 12px;
            cursor: pointer;
            margin: 1px 2px;
            transition: all 0.2s;
        }

        .fc-event:hover {
            opacity: 0.85;
            transform: translateY(-1px);
        }

        .fc-event-title {
            font-weight: 500;
        }

        .fc-daygrid-event-dot {
            display: none;
        }

        .fc-timegrid-slot {
            height: 48px;
        }

        .fc-timegrid-slot-label {
            font-size: 12px;
            color: #70757a;
        }

        /* Modal Styles */
        .modal-content {
            border: none;
            border-radius: 12px;
            box-shadow: 0 8px 24px rgba(0, 0, 0, 0.15);
        }

        .modal-header {
            background: white;
            border-bottom: 1px solid var(--border-color);
            padding: 20px 24px;
            border-radius: 12px 12px 0 0;
        }

        .modal-title {
            font-size: 18px;
            font-weight: 500;
            color: #3c4043;
        }

        .modal-body {
            padding: 24px;
        }

        .form-label {
            font-size: 14px;
            font-weight: 500;
            color: #3c4043;
            margin-bottom: 8px;
            display: flex;
            align-items: center;
            gap: 8px;
        }

        .form-control,
        .form-select {
            border: 1px solid var(--border-color);
            border-radius: 4px;
            padding: 10px 12px;
            font-size: 14px;
            transition: all 0.2s;
        }

        .form-control:focus,
        .form-select:focus {
            border-color: var(--google-blue);
            box-shadow: 0 0 0 2px rgba(26, 115, 232, 0.1);
            outline: none;
        }

        .btn-primary {
            background: var(--google-blue);
            border: none;
            color: white;
            padding: 10px 24px;
            border-radius: 4px;
            font-size: 14px;
            font-weight: 500;
            transition: all 0.2s;
        }

        .btn-primary:hover {
            background: var(--google-blue-hover);
        }

        .btn-secondary {
            background: white;
            border: 1px solid var(--border-color);
            color: #5f6368;
            padding: 10px 24px;
            border-radius: 4px;
            font-size: 14px;
            font-weight: 500;
            transition: all 0.2s;
        }

        .btn-secondary:hover {
            background: var(--hover-bg);
        }

        /* Toast Notification */
        .toast-notification {
            position: fixed;
            top: 20px;
            right: 20px;
            background: white;
            padding: 16px 20px;
            border-radius: 8px;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
            z-index: 9999;
            display: flex;
            align-items: center;
            gap: 12px;
            min-width: 300px;
            animation: slideIn 0.3s ease;
        }

        @keyframes slideIn {
            from {
                transform: translateX(400px);
                opacity: 0;
            }

            to {
                transform: translateX(0);
                opacity: 1;
            }
        }

        .toast-notification.success {
            border-left: 4px solid #34a853;
        }

        .toast-notification.error {
            border-left: 4px solid #ea4335;
        }

        .toast-notification.info {
            border-left: 4px solid #4285f4;
        }

        /* Google Places Autocomplete styling */
        .pac-container {
            z-index: 10000 !important;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.2);
            margin-top: 2px;
        }

        .pac-item {
            padding: 10px;
            cursor: pointer;
            font-size: 14px;
        }

        .pac-item:hover {
            background-color: #f1f3f4;
        }

        .pac-icon {
            margin-right: 10px;
        }

        .pac-item-query {
            font-weight: 600;
            color: #202124;
        }

        /* Team and Category Selection Styles */
        .equal-box {
            min-height: 120px;
            background-color: #f8f9fa;
            border-radius: 8px;
            padding: 15px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        }

        .equal-box label {
            font-weight: 600;
            margin-bottom: 8px;
            color: #333;
            display: flex;
            align-items: center;
            gap: 5px;
        }

        .equal-box select,
        .equal-box input {
            width: 100%;
            padding: 8px 10px;
            font-size: 14px;
            border: 1px solid #ced4da;
            border-radius: 6px;
            box-shadow: none;
            background-color: #fff;
        }

        .equal-box select:focus,
        .equal-box input:focus {
            border-color: #86b7fe;
            outline: none;
            box-shadow: 0 0 0 0.15rem rgba(13, 110, 253, 0.25);
        }

        .form-section {
            display: flex;
            gap: 20px;
        }

        .form-section .col-md-6 {
            flex: 1;
        }

        /* Responsive */
        @media (max-width: 768px) {
            .calendar-sidebar {
                position: fixed;
                left: -280px;
                z-index: 1000;
                height: 100vh;
                transition: left 0.3s;
            }

            .calendar-sidebar.open {
                left: 0;
            }
        }

        /* sidebar scrollable.. */
        .calendar-sidebar,
        {
        display: flex;
        flex-direction: column;
        /* height: 100vh; */
        width: 300px;
        background: #fff;
        border-right: 1px solid #e0e0e0;
        position: sticky;
        top: 0;
        overflow: hidden;
        }

        .sidebar-header {
            background: #fff;
            border-bottom: 1px solid #e0e0e0;
            flex-shrink: 0;
            z-index: 10;
        }

        .sidebar-scrollable {
            flex: 1;
            overflow-y: auto;
            padding: 16px;
            padding-top: 0;
        }

        .sidebar-scrollable::-webkit-scrollbar {
            width: 6px;
        }

        .sidebar-scrollable::-webkit-scrollbar-track {
            background: #f1f1f1;
            border-radius: 10px;
        }

        .sidebar-scrollable::-webkit-scrollbar-thumb {
            background: #c1c1c1;
            border-radius: 10px;
        }

        .sidebar-scrollable::-webkit-scrollbar-thumb:hover {
            background: #a8a8a8;
        }
    </style>
@endpush
