name: Deploy project to our server
on:
  push:
    branches:
      - deploy

jobs:
  FTP-Deploy-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: SFTP Deploy
        uses: wangyucode/sftp-action@v1
        with:
          server: ftp.thewarriors.team
          port: 22
          username: oc@oc-workforce.thewarriors.team
          password: "mb;zA^8z3?QsU,*H"
          local_path: "./"
          remote_path: "/public_html"
